version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 eventcalendar.wsgi:application
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db # Referenciar o serviço db diretamente
    env_file:
      - .env # Adiciona o arquivo .env
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}
    entrypoint: ["/bin/bash", "./entrypoint.sh"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
