# Generated by Django 3.2.21 on 2023-10-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20210717_1606'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineevents',
            name='id_routine_event',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routineevents',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='calendarapp.event'),
        ),
    ]
