# Generated by Django 3.2.21 on 2023-10-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20231024_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='privacity',
            new_name='privacy',
        ),
    ]
