# Generated by Django 3.2.21 on 2023-10-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_rename_privacity_routine_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineevent',
            name='user',
        ),
    ]
