# Generated by Django 3.2.21 on 2023-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_remove_routineevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='privacy',
        ),
        migrations.AddField(
            model_name='routine',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
