# Generated by Django 3.2.21 on 2023-11-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20231114_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='routineevent',
            name='is_deleted',
        ),
    ]
