# Generated by Django 3.2.21 on 2023-11-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
